defaults:
  - _self_
  - autoresearch: default
  - paths: default
  - datamodule: dummy
  - model: mlp
  - plmodule: classifier
  - trainer: default
  - callbacks: default
  - logger: aim
  - opt: default
  - accelerate: default
  - experiment: null

task_name: train
tags: ["dev", "{{ preset }}"]
seed: 42

hydra:
  run:
    dir: outputs/${task_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${task_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  job:
    chdir: false
