from __future__ import annotations


def render_help() -> str:
    return "\n".join(
        [
            "aimx - a safe companion CLI for native Aim",
            "",
            "Owned commands:",
            "  help       Show this help message",
            "  version    Show the aimx version and detected native Aim version",
            "  doctor     Show native Aim availability and passthrough readiness",
            "  query      Query metrics, images, or run params from a local Aim repository",
            "             Usage: aimx query <metrics|images|params> [<expression>] [--repo <path>]",
            "             Options: --json  --oneline  --no-color  --verbose",
            "                      --steps start:end | --epochs start:end  (mutually exclusive)",
            "                      --head N  --tail N  --every K",
            "                      --max-images N  (images only, TTY rendering cap; default 6)",
            "                      --param KEY  (params only, repeatable selected parameter)",
            "             Repo defaults to the current directory; paths may point at either",
            "             the repo root or its .aim directory",
            "             If expression is omitted, aimx uses: run.hash != ''",
            "             Short run hashes in the expression are transparently expanded.",
            "             Params output includes run duration when available.",
            "             Example: aimx query metrics --repo data",
            "             Example: aimx query images --repo data --plain",
            "             Example: aimx query params --repo data --json",
            "             Example: aimx query metrics \"run.hash=='eca37394'\" --repo data",
            "             Example: aimx query images \"images\" --repo data --epochs 10:50",
            "             Example: aimx query images \"images\" --repo data --head 10",
            "             Example: aimx query params \"run.experiment=='cloud-segmentation'\" --repo data --param hparam.lr",
            "  trace      Plot metric time-series or distribution histograms from a local Aim repository",
            "             Usage: aimx trace [<expression>] [--repo <path>]",
            "             Usage: aimx trace distribution [<expression>] [--repo <path>]",
            "             Options: --table  --csv  --json",
            "                      --steps start:end  (e.g. --steps 100:500, :50, 100:)",
            "                      --step N  (distribution visual mode only; nearest tracked step)",
            "                      --head N  --tail N  --every K",
            "                      --width W  --height H  --no-color",
            "             Repo defaults to the current directory.",
            "             If expression is omitted, aimx uses: run.hash != ''",
            "             Short run hashes in the expression are transparently expanded.",
            "             Example: aimx trace --repo data --head 5",
            "             Example: aimx trace distribution --repo data --head 2 --no-color",
            "             Example: aimx trace \"metric.name=='loss'\" --repo data --steps 100:500",
            "             Example: aimx trace distribution \"distribution.name != ''\" --repo data --step 12300",
            "             Example: aimx trace distribution \"distribution.name=='weights'\" --repo data --table",
            "             Example: aimx trace distribution \"distribution.name=='weights'\" --repo data --json",
            "  research   Read or update durable Aimx research state and agent context",
            "             Usage: aimx research <state|update|context|agenda|next> ...",
            "             Reads are side-effect free; explicit update writes only .aimx/research.",
            "             Example: aimx research state --repo data --json",
            "             Example: aimx research context --repo data --objective \"improve accuracy\" --budget 12000 --json",
            "             Example: aimx research update --repo data --file update.json --json",
            "  finding    Inspect or steer durable research findings",
            "             Usage: aimx finding <ls|show|comment|accept|reject|assess> ...",
            "             Reads do not write .aimx; comment/accept/reject/assess are explicit writes.",
            "             Example: aimx finding ls --repo data --json",
            "             Example: aimx finding accept <finding-id> --reason \"carry forward\" --repo data",
            "  lineage    Inspect or edit relationships between findings",
            "             Usage: aimx lineage <show|link|retract> ...",
            "             Example: aimx lineage show <finding-id> --repo data --json",
            "             Example: aimx lineage link <source-id> challenges <target-id> --repo data",
            "  frontier   Inspect or steer project-defined research frontier",
            "             Usage: aimx frontier <show|lane-add|add|move|pause|retire> ...",
            "             Example: aimx frontier show --repo data --json",
            "             Example: aimx frontier pause <item-id> --reason \"review\" --repo data",
            "",
            "All other commands are delegated to native `aim`.",
        ]
    )
